import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ArticleList from "@/components/ArticleList";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ newsArticles }) {
  console.log("newsArticles >>>>>>", newsArticles);
  return (
    <>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleList newsArticles={newsArticles} />
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    ` https://jsonplaceholder.typicode.com/posts?_limit=6 `
  );
  const newsArticles = await res.json();

  return {
    props: {
      newsArticles,
    },
  };
};
